# Generated by Django 4.0.6 on 2022-07-07 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Product')),
                (
                    'product_normalized',
                    models.CharField(blank=True, max_length=100, null=True, verbose_name='Product normalized'),
                ),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenue')),
                ('sales_number', models.IntegerField(default=0, verbose_name='Sales Number')),
                ('date', models.DateField(verbose_name='Date')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'
                    ),
                ),
            ],
            options={
                'unique_together': {('product_normalized', 'user', 'date')},
            },
        ),
    ]
