# Generated by Django 4.0.6 on 2022-07-07 08:17
import os
from pathlib import Path

from django.db import migrations, transaction

from sales.utils import import_sales_from_csv

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'Trial Assignment Products List Django.csv'


def add_sales(apps, schema_editor):
    Sale = apps.get_model('sales', 'Sale')
    User = apps.get_model('users', 'User')
    user_one = User.objects.get(email='test_user@meistery.net')
    user_two = User.objects.get(email='test_user2@meistery.net')
    fixture_file = Path(os.path.join(fixture_dir, fixture_filename))

    with transaction.atomic():
        import_sales_from_csv(Sale, fixture_file, user_one.id)
        import_sales_from_csv(Sale, fixture_file, user_two.id)


def drop_sales(apps, schema_editor):
    Sale = apps.get_model('sales', 'Sale')
    Sale.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('sales', '0001_initial'),
        ('users', '0002_load_fixtures'),
    ]

    operations = [
        migrations.RunPython(add_sales, drop_sales),
    ]
